---
kind: Deployment
apiVersion: apps/v1
metadata:    
  name: dep-served-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  template:
    metadata:
      name: dep-pod-served-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      labels:
        app: dep-served-{{ .Iteration }}-{{ .Replica }}
    spec:
      containers:
      - args:
        - sleep
        - infinity
        name: app
        image: k8s.gcr.io/pause:3.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '100Mi'
            cpu: 100m
          limits:
            memory: '100Mi'
            cpu: 100m
      - name: sleep-1
        image: gcr.io/google_containers/pause-amd64:3.0
        resources:
          requests:
            memory: '100Mi'
            cpu: 100m
          limits:
            memory: '100Mi'
            cpu: 100m
  replicas: 2
  selector:
    matchLabels:
     app: dep-served-{{ .Iteration }}-{{ .Replica }}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate

