---
kind: Deployment
apiVersion: apps/v1
metadata:    
  name: dep-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  namespace: serving-ns-{{ .Iteration }}
spec:
  template:
    metadata:
      name: pod-serving-no-frr-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      namespace: serving-ns-{{ .Iteration }}
      annotations:
        gateway-ip: "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}"
        k8s.ovn.org/routing-namespaces: served-ns-{{ .Iteration }}
        k8s.ovn.org/routing-network: serving-ns-{{ .Iteration }}/sriov-net-{{ .Iteration }}
        k8s.v1.cni.cncf.io/networks: |-
          [{ "name": "sriov-net-{{ .Iteration }}", "ips": [ "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}/21" ]}]
        k8s.v1.cni.cncf.io/network-status: |-
          [{
              "name": "serving-ns-{{ .Iteration }}/sriov-net-{{ .Iteration }}",
              "interface": "net1",
              "ips": [
                  "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}"
                ],
              "dns": {}
          }]
      labels:
        serving: true-{{ .Replica }}          
    spec:
      containers:
      - name: nobfd
        image: quay.io/mukrishn/jetski:latest
        command: ["/bin/sh","-c"]
        args: ["sleep infinity"]
      - name: patch
        image: quay.io/mukrishn/jetski:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args:
        - sleep infinity # 10 && bash /var/tmp/patch_script.sh && sleep infinity
        volumeMounts:
        - name: kubeconfig
          mountPath: /tmp/
        - name: patch-script
          mountPath: /var/tmp/
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        - name: pod_name
          value: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      volumes:
        - name: config-volume
          configMap:
            name: frr
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        - name: patch-script
          configMap:
            name: patch-script
  replicas: 1
  selector:
    matchLabels:
     serving: true-{{ .Replica }}
  strategy:
    type: RollingUpdate 
