apiVersion: v1
kind: Pod
metadata:
  name: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  namespace: serving-ns-1
  annotations:
    gateway-ip: "192.168.{{ add 217 .Replica }}.{{ .Iteration }}"
    k8s.ovn.org/routing-namespaces: served-ns-1
    k8s.ovn.org/routing-network: serving-ns-1/sriov-net-1
    k8s.ovn.org/bfd-enabled: ""
    k8s.v1.cni.cncf.io/networks: |-
      [{ "name": "sriov-net-1", "ips": [ "192.168.{{ add 217 .Replica }}.{{ .Iteration }}/21" ]}]
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "serving-ns-1/sriov-net-1",
          "interface": "net1",
          "ips": [
              "192.168.{{ add 217 .Replica }}.{{ .Iteration }}"
            ],
          "dns": {}
      }]
spec:
  containers:
  - name: bfd
    image: quay.io/fpaoline/ovnkbfdtest:0.2
    command: ["/bin/sh","-c"]
    args: ["/usr/lib/frr/frrinit.sh start && sleep infinity"]
    ports:
    - containerPort: 3784
      protocol: UDP
    securityContext:
      privileged: true
    volumeMounts:
    - name: config-volume
      mountPath: /etc/frr
  - name: patch
    image: quay.io/mukrishn/jetski:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c"]
    args:
    - sleep 10 && bash /var/tmp/patch_script.sh && sleep infinity
    volumeMounts:
    - name: kubeconfig
      mountPath: /tmp/
    - name: patch-script
      mountPath: /var/tmp/
    env:
    - name: KUBECONFIG
      value: "/tmp/config"
    - name: pod_name
      value: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  volumes:
    - name: config-volume
      configMap:
        name: frr
    - name: kubeconfig
      secret:
        secretName: kubeconfig
    - name: patch-script
      configMap:
        name: patch-script


