---
kind: Deployment
apiVersion: apps/v1
metadata:    
  name: dep-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  namespace: serving-ns-{{ .Iteration }}
spec:
  template:
    metadata:
      name: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      namespace: serving-ns-{{ .Iteration }}
      annotations:
        gateway-ip: "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}"
        k8s.ovn.org/routing-namespaces: served-ns-{{ .Iteration }}
        k8s.ovn.org/routing-network: serving-ns-{{ .Iteration }}/sriov-net-{{ .Iteration }}
        k8s.ovn.org/bfd-enabled: ""
        k8s.v1.cni.cncf.io/networks: |-
          [{
              "name": "sriov-net-{{ .Iteration }}",
              "ips": [ "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}/21" ]
          }]
        k8s.v1.cni.cncf.io/network-status: |-
          [{
              "name": "serving-ns-{{ .Iteration }}/sriov-net-{{ .Iteration }}",
              "interface": "net1",
              "ips": [ "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}" ],
              "dns": {}
          }]
      labels:
        serving: true-{{ .Replica }}
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: bfd
        image: quay.io/wcaban/frr
        command:
          - sh
          - -c
          - >-
             cp /config/* /etc/frr/ &&
             for i in {2..254}; do echo " peer $(kubectl get nodes -o jsonpath='{.items[0].metadata.annotations.k8s\.ovn\.org\/node-primary-ifaddr}' | cut -d '"' -f4- | sed 's/\.[^.]*$//').$i" >> /etc/frr/frr.conf; done &&
             echo "  no shutdown" >> /etc/frr/frr.conf &&
             echo " !" >> /etc/frr/frr.conf &&
             echo "! subnets for each node" >> /etc/frr/frr.conf &&
             kubectl get nodes -o jsonpath='{range .items[*].metadata.annotations}{.k8s\.ovn\.org\/node\-subnets}{.k8s\.ovn\.org\/node\-primary\-ifaddr}{"\n"}{end}' | awk -F'["/]' '{print "ip route " $4"/"$5 " " $9}' >> /etc/frr/frr.conf &&
             ip a a 172.18.0.10/32 dev lo &&
             /usr/libexec/frr/frrinit.sh start &&
             tail -f /tmp/frr.log
        ports:
        - name: bfd
          containerPort: 3784
          protocol: UDP
        - name: stats
          containerPort: 9000
          protocol: TCP
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - >-
                vtysh -c 'show bfd peers brief' |
                grep up
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN", "NET_BIND_SERVICE"]
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: pre-install
            mountPath: /etc/pre-install
      - name: patch
        image: quay.io/mukrishn/jetski:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args:
        - sleep infinity # 10 && bash /var/tmp/patch_script.sh && sleep infinity
        volumeMounts:
        - name: kubeconfig
          mountPath: /tmp/
        - name: patch-script
          mountPath: /var/tmp/
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        - name: pod_name
          value: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      volumes:
        - name: pre-install
          emptyDir: {}
        - name: config-volume
          configMap:
            name: frr
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        - name: patch-script
          configMap:
            name: patch-script
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker-spk
                operator: Exists
  replicas: 1
  selector:
    matchLabels:
     serving: true-{{ .Replica }}
  strategy:
    type: RollingUpdate  

