---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: {{ .ES_INDEX }}
  indexerConfig:
    enabled: {{ .INDEXING }}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ range $index, $val := sequence 1 35 }}
  - name: service-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: regular-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service.yml
        replicas: 1
{{ end }}

{{ range $index, $val := sequence 1 34 }}
  - name: served-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: regular-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 20s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 60
{{ end }}

  - name: served-job-35
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: regular-ns-35
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 60
