---

jobs:

  - name: delete-job
    jobType: delete
    qps: 20
    burst: 20
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: init-served-job}

      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: serving-job}

      {{ if contains .SRIOV "true" }}
      - apiVersion: sriovnetwork.openshift.io/v1
        kind: SriovNetwork
        labelSelector: {kube-burner-job: create-networks-job}
      {{ end }}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: create-cms-job}

      - apiVersion: v1
        kind: Secret
        labelSelector: {kube-burner-job: create-secrets-job}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: init-job}

      - apiVersion: project.openshift.io/v1
        kind: Project
        labelSelector: {kube-burner-job: init-served-job}

      - apiVersion: project.openshift.io/v1
        kind: Project
        labelSelector: {kube-burner-job: init-job}
