global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: {{ .ES_INDEX }}
  indexerConfig:
    enabled: {{ .INDEXING }}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ $servedLimit := multiply .LIMITCOUNT .SCALE }}
{{ range $index, $val := sequence 1 $servedLimit }}
  - name: kubelet-density-heavy-{{ $val }}
    jobIterations: 1
    jobType: create
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: served-ns-{{ $val }}
    waitWhenFinished: true
    cleanup: false
    verifyObjects: true
    errorOnVerify: false
    podWait: false
    objects:

      - objectTemplate: objectTemplates/postgres-deployment.yml
        replicas: 30

      - objectTemplate: objectTemplates/app-deployment.yml
        replicas: 30
        inputVars:
          readinessPeriod: 10

      - objectTemplate: objectTemplates/postgres-service.yml
        replicas: 30

{{ end }}

