---
 
global:
  writeToFile: false
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false
    esServers: {{ .ES_SERVER }}
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
        
{{ $servedLimit := multiply 35 .SCALE }}
{{ range $index, $val := sequence 1 $servedLimit }}
  - name: delete-job-{{ $val }}
    jobType: delete
    jobIterations: 1
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Secret
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: job-{{ $val }}}
{{ end }}

  - name: delete-jobs
    jobType: delete
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    objects:
{{ range $index, $val := sequence 1 5 }}    
      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
        
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
{{ end }}

