---
 
global:
  indexerConfig:
    enabled: false
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ $normalLimit := mul .LIMITCOUNT .SCALE | int }}
{{ range $index, $val := untilStep 1 (add $normalLimit 1|int) 1 }}
  - name: delete-service-job-{{ $val }}
    jobType: delete
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    objects:
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: normal-service-job-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: normal-job-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: served-service-job-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: served-job-{{ $val }}}   

      - apiVersion: project.openshift.io/v1
        kind: Project
        labelSelector: {kube-burner-job: normal-service-job-{{ $val }}}
{{ end }}

