---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: kube-burner
  indexerConfig:
    enabled: true
    esServers: [https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic

jobs:

jobs:
  - name: node-density
    jobType: create
    jobIterations: 33
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns
    podWait: false
    verifyObjects: true
    errorOnVerify: true
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1

      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 60


  - name: f5-job
    jobType: create
    jobIterations: 35
    qps: {{ .QPS }}
    burst: {{ .QPS }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns
    podWait: true
    verifyObjects: true
    errorOnVerify: false
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_f5.yml
        replicas: 3
      - objectTemplate: objectTemplates/node_density_pod_served_f5.yml
        replicas: 3