---

global:
  measurements:
    - name: podLatency
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: {{ .INDEXING }}

jobs:
{{ range $index, $val := untilStep 1 34 1 }}
  - name: service-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    preLoadImages: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1
{{ end }}

{{ range $index, $val := untilStep 1 34 1 }}
  - name: normal-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    preLoadImages: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 20s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 60
{{ end }}

{{ range $index, $val := untilStep 1 36 1 }}
  - name: service-job-2-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    preLoadImages: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}
{{ end }}

{{ range $index, $val := untilStep 1 35 1 }}
  - name: served-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    preLoadImages: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 5s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}
{{ end }}

  - name: served-job-35
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-35
    podWait: false
    preLoadImages: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served_f5.yml
        replicas: 3
        inputVars:
          ns: 35
