---
 
global:
  measurements:
    - name: podLatency
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
  # - name: delete-networks-job
  #  jobType: delete
  #  namespace: openshift-sriov-network-operator
  #  objects:
  #  - kind: SriovNetwork
  #    labelSelector: {kube-burner-job: create-networks-job}

  # - name: delete-init-pods-job
  #   jobType: delete
  #   objects:
  #   - kind: Pod
  #     labelSelector: {kube-burner-job: init-job}
        
{{ $normalLimit := mul .LIMITCOUNT .SCALE | int }}
{{ range $index, $val := untilStep 1 (add $normalLimit 1|int) 1 }}
  - name: job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }} 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/cluster_density_configmap.yml
        replicas: 30
      - objectTemplate: objectTemplates/cluster_density_secret.yml
        replicas: 38
      - objectTemplate: objectTemplates/cluster_density_dep_served_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}       
      - objectTemplate: objectTemplates/cluster_density_pod_service_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}            
      - objectTemplate: objectTemplates/cluster_density_dep_served.yml
        replicas: 17
      - objectTemplate: objectTemplates/cluster_density_dep_service.yml
        replicas: 17
{{ end }}

  - name: app-job-1
    jobType: create
    jobIterations: {{ mul 2 .SCALE }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 84
        inputVars:
          ns: group-a-1
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-a-1

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 56
        inputVars:
          ns: group-b-1
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-b-1

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 25
        inputVars:
          ns: group-c-1
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-c-1

  - name: app-job-2
    jobType: create
    jobIterations: {{ mul 2 .SCALE }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
{{ range $index, $val := untilStep 1 4 1 }}
      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 24
        inputVars:
          ns: group-d-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-d-{{ $val }}

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 14
        inputVars:
          ns: group-e-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-e-{{ $val }}                       
{{ end }}

  - name: app-job-3
    jobType: create
    jobIterations: {{ mul 2 .SCALE }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
{{ range $index, $val := untilStep 1 7 1 }}
      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 12
        inputVars:
          ns: group-f-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-f-{{ $val }}

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 10
        inputVars:
          ns: group-g-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-g-{{ $val }}

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 9
        inputVars:
          ns: group-h-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-h-{{ $val }}                             
{{ end }}

  - name: app-job-4
    jobType: create
    jobIterations: {{ mul 2 .SCALE }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
{{ range $index, $val := untilStep 1 13 1 }}
      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 8
        inputVars:
          ns: group-i-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-i-{{ $val }}

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 6
        inputVars:
          ns: group-j-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-j-{{ $val }}

      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 5
        inputVars:
          ns: group-k-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-k-{{ $val }}                             
{{ end }}

  - name: app-job-5
    jobType: create
    jobIterations: {{ mul 2 .SCALE }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: true
    cleanup: false
    namespace: f5-served-ns 
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
{{ range $index, $val := untilStep 1 30 1 }}
      - objectTemplate: objectTemplates/cluster_density_dep_served_ports.yml
        replicas: 4
        inputVars:
          ns: group-l-{{ $val }}
      - objectTemplate: objectTemplates/cluster_density_pod_service_ports.yml
        replicas: 1
        inputVars:
          ns: group-l-{{ $val }}                   
{{ end }}
