---
 
global:
  writeToFile: false
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ $normalLimit := multiply .LIMITCOUNT .SCALE }}
{{ range $index, $val := sequence 1 $normalLimit }}
  - name: delete-service-job-{{ $val }}
    jobType: delete
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    objects:
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: service-job-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: normal-job-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: service-job-2-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: served-job-{{ $val }}}        
{{ end }}


