---
 
global:
  indexerConfig:
    enabled: false
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
        
{{ $servedLimit := mul .LIMITCOUNT .SCALE | int }}
{{ range $index, $val := untilStep 1 (add $servedLimit 1|int) 1 }}
  - name: delete-job-{{ $val }}
    jobType: delete
    jobIterations: 1
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Secret
        labelSelector: {kube-burner-job: job-{{ $val }}}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: job-{{ $val }}}
{{ end }}

  - name: delete-jobs
    jobType: delete
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    objects:
{{ range $index, $val := untilStep 1 6 1 }}    
      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
        
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
{{ end }}

