---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: {{ .ES_INDEX }}
  indexerConfig:
    enabled: {{ .INDEXING }}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ $normalLimit := multiply 35 .SCALE }}
{{ range $index, $val := sequence 1 $normalLimit }}
  - name: normal-service-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1
{{ end }}

{{ range $index, $val := sequence 1 $normalLimit}}
  - name: normal-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps:  {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 60
{{ end }}

{{ $servedLimit := multiply 35 .SCALE }}
{{ range $index, $val := sequence 1 $servedLimit }}
  - name: served-service-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1
{{ end }}

{{ $lastLimit := add $servedLimit -1 }}
{{ range $index, $val := sequence 1 $lastLimit }}
  - name: served-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 3
{{ end }}


  - name: served-job-{{ $servedLimit }}
    jobType: create
    jobIterations: 1
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $servedLimit }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 3

