---
global:
  gc: false
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: 2m0s
indexers:
  - esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING}}

jobs:

  - name: create-networks-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: {{ if contains .SRIOV "true" }} false {{ else }} true {{ end }}
    cleanup: false
    namespace: {{ if contains .SRIOV "true" }} openshift-sriov-network-operator {{ else }} serving-ns {{ end }}
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: {{ if contains .SRIOV "true" }} objectTemplates/sriov_network.yml {{ else }} objectTemplates/macvlan_network.yml {{ end }}
        replicas: 1
        inputVars:
          bridge: {{ .BRIDGE }}

  - name: create-serviceaccounts-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/permissionsServiceAccount.yml
        replicas: 1

  - name: create-clusterrole-job
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: default
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/permissionsClusterRole.yml
        replicas: 1

  - name: create-clusterbindings-jobs
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/permissionsClusterRoleBinding.yml
        replicas: 1

  - name: create-rolebindings-jobs
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/permissionsRoleBinding.yml
        replicas: 1

  - name: create-cms-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/cm_frr.yml
        replicas: 1

  - name: init-served-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: served-ns
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/pod_served.yml
        replicas: 1

{{ if contains .CRD "true" }}
  - name: init-externalroutes-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: default
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/adminPolicyBasedExternalRoute.yml
        replicas: 1
        inputVars:
          bfd: "{{ $.BFD }}"
          icni: "{{ $.ICNI }}"
{{ end }}

  - name: serving-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/pod_serving.yml
        replicas: 4
        inputVars:
          bfd: "{{ $.BFD }}"
          crd: "{{ $.CRD }}"
          icni: "{{ $.ICNI }}"
