---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: kube-burner
  indexerConfig:
    enabled: false
    esServers: [https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic

jobs:
{{ $servedLimit := multiply 35 .SCALE }}
  - name: delete-jobs
    jobType: delete
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    objects:
{{ range $index, $val := sequence 1 5 }}    
      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
        
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
{{ end }}

{{ range $index, $val := sequence 1 $servedLimit }}
  - name: delete-job-2-{{ $val }}
    jobType: delete
    jobIterations: 1
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Secret
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: project.openshift.io/v1
        kind: Project
        labelSelector: {kube-burner-job: job-2-{{ $val }}}
{{ end }}

