---

jobs:
{{ $servedLimit := mul .LIMITCOUNT .SCALE }}
  - name: delete-jobs
    jobType: delete
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    objects:
{{ range $index, $val := untilStep 1 6 1 }}    
      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
        
      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: app-job-{{ $val }}}
{{ end }}

{{ range $index, $val := untilStep 1 (add $servedLimit 1|int) 1 }}
  - name: delete-job-2-{{ $val }}
    jobType: delete
    jobIterations: 1
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Pod
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Service
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Secret
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: v1
        kind: Configmap
        labelSelector: {kube-burner-job: job-2-{{ $val }}}

      - apiVersion: project.openshift.io/v1
        kind: Project
        labelSelector: {kube-burner-job: job-2-{{ $val }}}
{{ end }}

