---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: {{ .ES_INDEX }}
  indexerConfig:
    enabled: {{ .INDEXING }}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ range $index, $val := sequence 1 33 }}
  - name: service-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1
{{ end }}

{{ range $index, $val := sequence 1 33}}
  - name: normal-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 30
{{ end }}

{{ range $index, $val := sequence 1 35 }}
  - name: service-job-2-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}
{{ end }}

{{ range $index, $val := sequence 1 35 }}
  - name: served-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: f5-served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served_f5.yml
        replicas: 3
        inputVars:
          ns: {{ $val }}
{{ end }}

{{ $normalLimit := multiply .LIMITCOUNT .SCALE }}
{{ range $index, $val := sequence 1 $normalLimit }}
  - name: icni2-service-job-{{ $val }}
    jobType: create
    jobIterations: 1       
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 1
{{ end }}

{{ range $index, $val := sequence 1 $normalLimit}}
  - name: icni2-served-job-{{ $val }}
    jobType: create
    jobIterations: 1
    qps:  {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: served-ns-{{ $val }}
    podWait: false
    waitWhenFinished: true
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    objects:
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 33
{{ end }}
