global:
  measurements:
    - name: podLatency
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{ .ES_INDEX }}
    type: elastic

jobs:
{{ $servedLimit := mul .LIMITCOUNT .SCALE | int }}
{{ range $val := untilStep 1 (add $servedLimit 1|int) 1 }}

  - name: kubelet-density-heavy-{{ $val }}
    jobIterations: 1
    jobType: create
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    namespace: served-ns-{{ $val }}
    waitWhenFinished: true
    cleanup: false
    verifyObjects: true
    errorOnVerify: false
    podWait: false
    preLoadImages: false
    objects:

      - objectTemplate: objectTemplates/postgres-deployment.yml
        replicas: 30

      - objectTemplate: objectTemplates/app-deployment.yml
        replicas: 30
        inputVars:
          readinessPeriod: 10

      - objectTemplate: objectTemplates/postgres-service.yml
        replicas: 30

{{ end }}

