apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: serving-lb-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  nicSelector:
    pfNames:
     - $sriov_nic
  nodeSelector:
    node-role.kubernetes.io/worker-lb: ""
  numVfs: 64
  resourceName: intelnics2

